services:
  telegram-files:
    container_name: telegram-files
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/api/health" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
    environment:
      APP_ENV: "prod"
      APP_ROOT: "/app/data"
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    ports:
      - "6543:80"
    volumes:
      - ./data:/app/data
    # - ./other-files-for-transfer:/app/other-files-for-transfer
