services:
  telegram-files:
    container_name: telegram-files
    image: ghcr.io/jarvis2f/telegram-files:latest
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "--timeout=3", "--tries=1", "http://localhost:8080/health" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_ROOT: ${APP_ROOT:-/app/data}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    ports:
      - "6543:80"
    volumes:
      - ./data:/app/data
