name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: [ "enhancement" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving the project! Please fill out this form to help us understand your feature request.

  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem?
      description: |
        A clear and concise description of what the problem is. For example: "I'm always frustrated when..."
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like the app to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've also thought about...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any relevant screenshots, mockups, or ideas...
    validations:
      required: false
